version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      - port=3000
    depends_on:
      - mongo
    # env-file:
    #   - ./.env

  mongo:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=pravidya2
    #   - MONGO_INITDB_ROOT_PASSWORD=prabat
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
