version: "3"

services:
  node-app:
    build:
      context: .
      arge:
        NODE_ENV: developent
    ports:
      - "3000:3000"
    environment:
      - port=3000
    # env-file:
    #   - ./.env
