version: "3"

services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production

    environment:
      - NODE-ENV=production
      - MONGO_USER=pravidya2
      - MONGO_PASSWORD=prabat

    command: node index.js
