version: "3"

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - port=3000
    # env-file:
    #   - ./.env

  mongo:
    image: mongo
    environment:
      - MONGO-INITDB_ROOT_USERNAME=pravidya2
      - MONGO_INITDB_ROOT_PASSWORD=prabat
